# Generated by Django 2.2.10 on 2020-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200525_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='twitch_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
