# Generated by Django 2.2.10 on 2020-05-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200526_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sponsor_supplier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitch_account',
        ),
    ]
