# Generated by Django 2.2.10 on 2020-06-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200528_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, choices=[('S', 'Sponsor Provider'), ('C', 'Content Creator'), ('P', 'Power User'), ('N', 'New User')], default='N', max_length=1, null=True),
        ),
    ]
