# Generated by Django 2.2.10 on 2020-06-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='cleared_hot',
            field=models.BooleanField(default=False),
        ),
    ]
