# Generated by Django 2.2.10 on 2020-06-02 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200602_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='account_type',
            new_name='role_name',
        ),
    ]
