# Generated by Django 2.2.10 on 2020-06-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200602_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroles',
            old_name='quantifier',
            new_name='fee_quantifier',
        ),
        migrations.AddField(
            model_name='userroles',
            name='time_quantifier',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
