# Generated by Django 2.2.10 on 2020-11-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201007_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
