# Generated by Django 2.2.10 on 2020-05-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200527_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='available_to_run',
            field=models.IntegerField(default=1),
        ),
    ]
