# Generated by Django 2.2.10 on 2020-05-29 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_orderitem_available_to_run'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_related_name': 'items', 'ordering': ['-price']},
        ),
    ]
