# Generated by Django 2.2.10 on 2020-05-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200528_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sponsor_supplier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitch_account',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
