# Generated by Django 2.2.10 on 2020-05-29 05:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200528_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expires_on',
            field=models.DateTimeField(default=core.models.get_deadline),
        ),
    ]
