# Generated by Django 2.2.10 on 2020-05-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_expires_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cleared_hot',
            field=models.BooleanField(default=False),
        ),
    ]
