# Generated by Django 2.2.10 on 2020-05-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_cleared_hot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiveawayStats',
        ),
    ]
