# Generated by Django 2.2.10 on 2020-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_giveawaystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
