# Generated by Django 2.2.10 on 2020-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(choices=[('D', 'default'), ('L', 'low'), ('H', 'high')], default='D', max_length=1),
        ),
    ]
