# Generated by Django 2.2.10 on 2020-06-02 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200602_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='giveaway_fee',
            field=models.FloatField(verbose_name='Amount to charge buyer'),
        ),
        migrations.AlterField(
            model_name='item',
            name='giveaway_value',
            field=models.FloatField(verbose_name='Amount to giveaway'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('S', 'Sponsor Provider'), ('C', 'Content Creator'), ('P', 'Power User'), ('N', 'New User')], default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
