# Generated by Django 2.2.10 on 2020-06-22 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checktime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Slotitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('available', models.IntegerField(default=20)),
                ('total', models.IntegerField(default=20)),
                ('points', models.IntegerField(default=100)),
                ('value', models.IntegerField(default=25)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.BooleanField(default=False)),
                ('instagram', models.BooleanField(default=False)),
                ('facebook', models.BooleanField(default=False)),
                ('tiktok', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='kind',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='braintree_charge_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('B', 'Braintree')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='braintree_customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('GW', 'Giveaway'), ('PW', 'Pick Winner'), ('SB', 'Social Boost'), ('PE', 'Profile Examine')], max_length=2),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('order_id', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Slotitem'),
        ),
    ]
