# Generated by Django 2.2.10 on 2020-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200623_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='kind',
            field=models.IntegerField(default=0),
        ),
    ]
