# Generated by Django 2.2.10 on 2020-06-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_order_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktime',
            name='launch_time',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='checktime',
            name='launched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checktime',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('S', 'Stripe'), ('B', 'Braintree'), ('P', 'Paypal')], max_length=1),
        ),
    ]
