# Generated by Django 2.2.10 on 2020-06-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200629_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
