# Generated by Django 2.2.10 on 2020-07-13 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_slotitem_description'),
    ]

    operations = [
        # migrations.AlterModelOptions(
        #     name='orderitem',
        #     options={'ordering': ['orders__ordered_date']},
        # ),
        # migrations.AlterModelOptions(
        #     name='slotitem',
        #     options={'ordering': ['title']},
        # ),
        # migrations.AddField(
        #     model_name='checktime',
        #     name='launch_code',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='orderitem',
        #     name='launch_code',
        #     field=models.CharField(blank=True, max_length=200, null=True),
        # ),
        # migrations.AddField(
        #     model_name='slotitem',
        #     name='available_count',
        #     field=models.IntegerField(default=20),
        # ),
        # migrations.AlterField(
        #     model_name='slotitem',
        #     name='available',
        #     field=models.BooleanField(default=True),
        # ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('T', 'To Cart'), ('E', 'Empty Cart'), ('R', 'Release Cart'), ('P', 'Purchased'), ('F', 'Refresh page'), ('S', 'Server Restart')], default='T', max_length=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=200)),
                ('item_str', models.CharField(max_length=200)),
                ('order_str', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
