# Generated by Django 2.2.10 on 2020-06-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_slotitem_description'),
    ]
 
    operations = [
        migrations.AddField(
            model_name='checktime',
            name='launch_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='launch_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
