# Generated by Django 2.2.10 on 2020-07-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200630_0754'),
    ]
 
    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['orders__ordered_date']},
        ),
        migrations.AlterModelOptions(
            name='slotitem',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='slotitem',
            name='available_count',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='slotitem',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
