# Generated by Django 2.2.10 on 2020-07-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200712_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='payment',
        ),
        migrations.AlterField(
            model_name='history',
            name='action_type',
            field=models.CharField(choices=[('T', 'To Cart'), ('E', 'Empty Cart'), ('R', 'Release Cart'), ('P', 'Purchased'), ('F', 'Refresh page'), ('S', 'Server Restart'), ('D', 'Delete timer'), ('N', 'Launch thread')], default='T', max_length=1),
        ),
    ]
