# Generated by Django 2.2.10 on 2020-07-12 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0021_auto_20200709_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('T', 'To Cart'), ('E', 'Empty Cart'), ('R', 'Release Cart'), ('P', 'Purchased')], default='T', max_length=1)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=200)),
                ('item_str', models.CharField(max_length=200)),
                ('order_str', models.CharField(max_length=100)),
                ('other', models.CharField(max_length=200)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
