# Generated by Django 2.2.10 on 2020-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200713_0550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'default_related_name': 'orders', 'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-orders__id']},
        ),
        migrations.RemoveField(
            model_name='history',
            name='action_type',
        ),
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.CharField(default='anything', max_length=200),
            preserve_default=False,
        ),
    ]
