# Generated by Django 2.2.10 on 2020-07-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200715_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Counting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0)),
                ('pause', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='checktime',
            name='action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checktime',
            name='cartcounter_run',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checktime',
            name='thread_id',
            field=models.IntegerField(default=1),
        ),
    ]
