# Generated by Django 2.2.10 on 2020-08-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200716_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-id']},
        ),
    ]
