# Generated by Django 2.2.10 on 2020-08-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200805_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='placeholder',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
