# Generated by Django 2.2.10 on 2020-08-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_item_placeholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='slotitem',
            name='placeholder',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
