# Generated by Django 2.2.10 on 2020-08-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20200815_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotitem',
            name='placeholder',
            field=models.CharField(blank=True, default='Enter username', max_length=250, null=True),
        ),
    ]
