# Generated by Django 2.2.10 on 2020-08-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200815_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(blank=True, choices=[('I', 'In Cart'), ('P', 'Purchased'), ('S', 'Scheduled'), ('L', 'Live'), ('T', 'Winner Selected'), ('C', 'Winner Contacted'), ('D', 'Winner Paid')], default='I', max_length=20, null=True),
        ),
    ]
