# Generated by Django 2.2.10 on 2020-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='username',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
