# Generated by Django 2.2.10 on 2020-11-06 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_old', models.IntegerField(blank=True, null=True)),
                ('follower_count', models.IntegerField(blank=True, null=True)),
                ('tweet_count', models.IntegerField(blank=True, null=True)),
                ('favorites', models.IntegerField(blank=True, null=True)),
                ('following', models.IntegerField(blank=True, null=True)),
                ('default_profile', models.BooleanField(default=True)),
                ('default_profile_image', models.BooleanField(default=False)),
                ('unique_background', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('giveaway_timeline_analysis', models.FloatField(default=0, null=True)),
                ('tweets_per_day', models.FloatField(default=0, null=True)),
                ('bot_prediction', models.BooleanField(default=False)),
                ('profile_grade', models.CharField(max_length=2, null=True)),
                ('date_analyzed', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
