# Generated by Django 2.2.10 on 2020-12-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_analyzer', '0002_profilejudgement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileanalysis',
            old_name='default_profile',
            new_name='default_profile_status',
        ),
    ]
