# Generated by Django 2.2.10 on 2020-12-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_analyzer', '0003_auto_20201210_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilejudgement',
            name='credits',
            field=models.IntegerField(default=1),
        ),
    ]
