# Generated by Django 2.2.10 on 2020-12-14 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_analyzer', '0004_profilejudgement_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilejudgement',
            name='date_analyzed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilejudgement',
            name='profile_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profile_analyzer.ProfileAnalysis'),
        ),
    ]
