# Generated by Django 2.2.10 on 2020-05-25 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retweet_picker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='twittergiveawayid',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twittergiveaway',
            name='giveaway_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_info', to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.AddField(
            model_name='twittergiveaway',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retweet_winners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='twittergiveaway',
            name='tweet_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_url', to='retweet_picker.TweetDetails'),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='winner',
            field=models.ManyToManyField(to='retweet_picker.ContestUserAccounts'),
        ),
        migrations.AddField(
            model_name='giveawayresults',
            name='giveaway_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_details', to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.AddField(
            model_name='giveawayresults',
            name='re_rolls',
            field=models.ManyToManyField(related_name='rerolled_user', to='retweet_picker.ContestUserAccounts'),
        ),
        migrations.AddField(
            model_name='giveawayresults',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giveaway_winner', to='retweet_picker.ContestUserAccounts'),
        ),
        migrations.AddField(
            model_name='contestuserparticipation',
            name='contest',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.AddField(
            model_name='contestuserparticipation',
            name='contestants',
            field=models.ManyToManyField(to='retweet_picker.ContestUserAccounts'),
        ),
    ]
