# Generated by Django 2.2.10 on 2020-05-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0002_auto_20200525_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twittergiveaway',
            name='tweet_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='original_url', to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.DeleteModel(
            name='TweetDetails',
        ),
    ]
