# Generated by Django 2.2.10 on 2020-05-29 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_giveawaystats'),
        ('retweet_picker', '0003_auto_20200529_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giveaway_start_time', models.DateTimeField(blank=True, null=True)),
                ('giveaway_end_time', models.DateTimeField(blank=True, null=True)),
                ('sponsor_start_follower_count', models.IntegerField(blank=True, null=True)),
                ('sponsor_end_follower_count', models.IntegerField(blank=True, null=True)),
                ('retweet_count', models.IntegerField(blank=True, null=True)),
                ('confirmation_tweet', models.URLField(blank=True, null=True, verbose_name='Confirmation Tweet')),
                ('giveaway_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway_stats', to='retweet_picker.TwitterGiveawayID')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='retweet_picker.ContestUserAccounts')),
            ],
        ),
    ]
