# Generated by Django 2.2.10 on 2020-08-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0005_auto_20200530_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveawayQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0)),
                ('item_id', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('L', 'Live'), ('R', 'Retrieve'), ('C', 'Choosed Winner'), ('E', 'End')], max_length=1)),
                ('queue_type', models.CharField(choices=[('H', 'High'), ('D', 'Default')], max_length=1)),
                ('duration', models.IntegerField(default=0)),
                ('tweet_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
