# Generated by Django 2.2.10 on 2020-10-06 13:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0007_auto_20200827_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_max', models.IntegerField(default=500)),
                ('price', models.IntegerField(default=1)),
                ('per_amount', models.IntegerField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='contestuseraccounts',
            name='profile_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contestuserparticipation',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='command',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='draw_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='drawed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='giveaway_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw_giveaway_details', to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='loaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='paid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('L', 'Loaded entries'), ('D', 'Drawing'), ('S', 'Drawing stoped'), ('W', 'Drawed')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='toload_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestuserparticipation',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.AlterField(
            model_name='giveawaywinners',
            name='winner',
            field=models.ManyToManyField(related_name='draw_giveaway_winner', to='retweet_picker.ContestUserAccounts'),
        ),
        migrations.CreateModel(
            name='Rerolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('kind', models.IntegerField(default=0)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retweet_picker.ContestUserAccounts')),
            ],
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='re_rolls',
            field=models.ManyToManyField(to='retweet_picker.Rerolls'),
        ),
    ]
