# Generated by Django 2.2.10 on 2020-09-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0008_auto_20200918_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_max', models.IntegerField(default=500)),
                ('price', models.IntegerField(default=1)),
                ('per_amount', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rerolls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retweet_picker.ContestUserAccounts')),
            ],
        ),
        migrations.AddField(
            model_name='contestuserparticipation',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='loaded_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('F', 'Loaded free'), ('P', 'Paid'), ('L', 'Loaded entries'), ('D', 'Drawed free'), ('W', 'Drawed finally')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='toload_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestuserparticipation',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retweet_picker.TwitterGiveawayID'),
        ),
        migrations.AlterField(
            model_name='giveawaywinners',
            name='re_rolls',
            field=models.ManyToManyField(to='retweet_picker.Rerolls'),
        ),
    ]
