# Generated by Django 2.2.10 on 2020-10-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0008_auto_20201006_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawaywinners',
            name='load_error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='giveawaywinners',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('E', 'Loading Error'), ('L', 'Loaded entries'), ('D', 'Drawing'), ('S', 'Drawing stoped'), ('W', 'Drawed')], default='C', max_length=1),
        ),
    ]
