# Generated by Django 2.2.10 on 2020-10-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0009_auto_20200925_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuseraccounts',
            name='profile_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='command',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='draw_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='drawed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='paid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rerolls',
            name='kind',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='giveawaywinners',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('L', 'Loaded entries'), ('D', 'Drawing'), ('S', 'Drawing stoped'), ('W', 'Drawed')], default='C', max_length=1),
        ),
    ]
