# Generated by Django 2.2.10 on 2020-11-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0011_membership_pricingplan_upgradeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawaywinners',
            name='follow_main',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='followers',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='membership',
            name='bonus_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='unlimited_count',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='unlimited_times',
            field=models.BooleanField(default=False),
        ),
    ]
