# Generated by Django 2.2.10 on 2020-11-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0012_auto_20201106_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestuserparticipation',
            old_name='user_id',
            new_name='kind',
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='bot_chk',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='giveawaywinners',
            name='rerolled_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='reroll_count',
            field=models.IntegerField(default=10),
        ),
    ]
