# Generated by Django 2.2.10 on 2020-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0013_auto_20201113_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawprice',
            name='queue_count',
            field=models.IntegerField(default=3),
        ),
    ]
