# Generated by Django 2.2.10 on 2021-02-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retweet_picker', '0016_membership_analyzed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='analyzed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='credit_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
