# Generated by Django 2.2.10 on 2021-01-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onevalue',
            name='judge_credit_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='onevalue',
            name='min_buy_credit',
            field=models.IntegerField(default=5),
        ),
    ]
