# Generated by Django 2.2.10 on 2020-07-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0002_auto_20200722_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawaypkandslug',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='giveawaypkandslug',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
