# Generated by Django 2.2.10 on 2020-07-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0003_auto_20200722_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveaway',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
