# Generated by Django 2.2.10 on 2020-07-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0005_giveawaypkandslug_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giveawaypkandslug',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
