# Generated by Django 2.2.10 on 2020-07-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0006_auto_20200723_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveawaypkandslug',
            name='giveaway_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
