# Generated by Django 2.2.10 on 2020-08-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0008_auto_20200723_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='gleam_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
