# Generated by Django 2.2.10 on 2020-08-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaways', '0009_giveaway_gleam_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='giveaway',
            name='gleam_graph_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
